### PR TITLE
Skill average

### PR DESCRIPTION
**Pull request by HyxonQz**
Added 'average' option to !skills command, uses skycrypt API

### CODE REVIEW

**Comment by aidn3** [comment]
Isn't it a bad idea to depend on external servers api. We have no control over. And for something as simple as that is overkill to make an external request.

**Comment by HyxonQz** [comment]
> Isn't it a bad idea to depend on external servers api. We have no control over. And for something as simple as that is overkill to make an external request.
weight command :p

**Comment by HyxonQz** [comment]
> > > Isn't it a bad idea to depend on external servers api. We have no control over. And for something as simple as that is overkill to make an external request.
> > 
> > 
> > weight command :p
> 
> It is bad already. That command sometimes doesn't work and some people have private messaged me asking about that. I do wish to convert weight to local as well. you can do it if you have time.

I will make both locally calculated then. Only issue is that I’ll also have to make custom interfaces for both since hypixels library is very outdated for skyblock

**Comment by aidn3** [comment]
Closing this since no updates here.

**Pull request closed without merging**
