### PR TITLE
Implementation of the RTCA command, in response to Add command to check for runs counts till Class average 50 #91

### PR DESCRIPTION
**Pull request by itsvyle**
Note that I had to do modifications to `discord-instance.ts` so that I can run tests without issues

### CODE REVIEW

**Comment by itsvyle** [comment]
Implementation for #91

**Comment by aidn3** [comment]
> Note that I had to do modifications to `discord-instance.ts` so that I can run tests without issues

You can commit certain files and ignore others.

**Comment by itsvyle** [comment]
wanted to make it easier to test ¯\_(ツ)_/¯

**Review by aidn3 — CHANGES_REQUESTED** [review]
Latest Hypixel updates has xp boost. @HyxonQz was able to contact Soopy (the original developer of this command) and managed to get some insights and code.

This is a modified version that should fit in our application.
```ts
// src/instance/commands/triggers/runstoclassavg.ts

    // raw profile is used to read essence
    // not sure if it exists in the processed version
    const parsedProfile = await context.app.hypixelApi
      .getSkyblockProfiles(uuid, { raw: true })
      .then((response) => response.profiles.find((p) => p.selected)?.members[uuid])
    assert(parsedProfile)

    const dungeonsData = parsedProfile.dungeons
    const coldEfficiency = parsedProfile.essence?.perks?.cold_efficiency ?? 0
    const heartOfGold = parsedProfile.essence?.perks?.heart_of_gold ?? 0
    const diamondInTheRough = parsedProfile.essence?.perks?.diamond_in_the_rough ?? 0
    const toxophilite = parsedProfile.essence?.perks?.toxophilite ?? 0
    const unbridledRage = parsedProfile.essence?.perks?.unbridled_rage ?? 0

    const classExpBoosts = {
      mage: (coldEfficiency * 2) / 100 + 1,
      archer: (toxophilite * 2) / 100 + 1,
      berserk: (unbridledRage * 2) / 100 + 1,
      healer: (heartOfGold * 2) / 100 + 1,
      tank: (diamondInTheRough * 2) / 100 + 1
    }
```

Need to declare Essence fields as well.
```ts
// src/types/hypixel-api-reborn.d.ts
  export interface SkyblockV2Member {
    leveling?: { experience: number }
    dungeons: SkyblockV2Dungeons
    nether_island_player_data: {
      kuudra_completed_tiers: {
        none: number
        hot: number
        burning: number
        fiery: number
        infernal: number
      }
    }
    slayer: SlayerProfile
    essence?: SkyblockV2Essence
  }

  export interface SkyblockV2Essence {
    perks?: SkyblockV2EssencePerks
  }
  export interface SkyblockV2EssencePerks {
    cold_efficiency?: number
    heart_of_gold?: number
    diamond_in_the_rough?: number
    toxophilite?: number
    unbridled_rage?: number
  }
```

This is how they are used. This is the original code and not modified to fit yours.
```ts
       tempClassData[key].xp += xpPer * 0.25 * classExpBoosts[key]
       ...
      tempClassData[temporaryClassPlaying].xp += xpPer * 0.75 * classExpBoosts[temporaryClassPlaying]
```

**Pull request merged**
